"""empty message

Revision ID: 4cf510b098ea
Revises: 
Create Date: 2020-10-26 18:19:30.683364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf510b098ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('subname', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=30), nullable=False),
    sa.Column('retail_price', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('colorway', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('subname')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('marketprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('size', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('seller', sa.String(length=30), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('search_query', sa.String(length=30), nullable=True),
    sa.Column('shoesmodel_id', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['shoesmodel_id'], ['shoes.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platformprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('saleday', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['shoes.code'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platformprice')
    op.drop_table('marketprice')
    op.drop_table('user')
    op.drop_table('shoes')
    # ### end Alembic commands ###
