"""empty message

Revision ID: 93726435b950
Revises: 4cf510b098ea
Create Date: 2020-10-27 13:33:28.683726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93726435b950'
down_revision = '4cf510b098ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platformprice', sa.Column('search_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platformprice', 'search_date')
    # ### end Alembic commands ###
